[package]
name = "harald-lang"
version = "0.0.1"
authors = ["paavohuhtala <paavo.huhtala@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1.2"
rand = "0.7.3"
thiserror = "1.0.20"
anyhow = "1.0.32"

[lib]
name = "harald"
path = "src/lib.rs"

[[bin]]
name = "haraldi"
path = "src/main.rs"